### PR TITLE
Silence some compiler warnings about unused imports

### PR DESCRIPTION
**Pull request by therealprof**
While trying something with the tests I noticed that there're some unused import warnings which can easily be silenced.

### CODE REVIEW

**Comment by schungx** [comment]
Well, currently the coding style is that unused imports are OK in tests and other non-lib places.

Rhai has a large number of features and silencing all warnings will need to explicitly qualify a lot of things in lots of places.

We try to silence warnings for lib code so projects using Rhai won't get unnecessary compile warnings

**Comment by therealprof** [comment]
I do find the warnings very distracting as I was looking into improving the #899 situation and I'm also not attempting to fix the remaining 2 or 3 gnarlier ones. But I'm fine closing this PR if you don't want to address this cosmetic issue.

**Comment by schungx** [comment]
Let's run the CI and see...

**Comment by schungx** [comment]
Closing this for now.

**Pull request closed without merging**
