### PR TITLE
Native module

### PR DESCRIPTION
**Pull request by ltabis**
I would like to change the visibility of the `func::native` module to public to be able to use functions like `locked_read` & `locked_write` for `rhai-dylib`'s module resolver implementation. Is a simple re-export enough or should we lock the export behind a feature gate ?

### CODE REVIEW

**Comment by schungx** [comment]
I can make them public...  no particular harm in doing that.  Or gate them under `internals`?

They are just simple wrappers, you can simply copy them over.

**Comment by schungx** [comment]
Oops, forgot about this and I just released `1.11.0`.  Oh well, we can always add this to `1.11.1`...  ;-)

**Comment by ltabis** [comment]
> Oops, forgot about this and I just released `1.11.0`. Oh well, we can always add this to `1.11.1`... ;-)
I've synced the fork :)

**Comment by ltabis** [comment]
@schungx done, `func::native` is public under the `internals` feature.

**Comment by schungx** [comment]
Actually, I would prefer to cherry-pick the functions that are useful to be exported...  There is probably not much use to export the internal types for function signatures...

Say `pub func::native::{locked_read, locked_write};`

**Pull request merged**
