### PR TITLE
Empty for Arrays

### PR DESCRIPTION
**Pull request by ltabis**
Would it be interesting to have an `empty` getter on arrays to check if they're empty instead of using `array.len == 0` ?

### CODE REVIEW

**Comment by schungx** [comment]
It probably should be called `is_empty` similar to Rust...

But I hesitate to add such a function as we'd need to add it for all other data types to be consistent...

**Comment by schungx** [comment]
It probably should be called `is_empty` similar to Rust...

But I hesitate to add such a function as we'd need to add it for all other data types to be consistent...

**Comment by ltabis** [comment]
> But I hesitate to add such a function as we'd need to add it for all other data types to be consistent...

Except for `map` and `string`, which other type would need the `is_empty` function ?

**Comment by schungx** [comment]
Probably BLOBs, ranges, ...

**Comment by ltabis** [comment]
I've added `is_empty` to map, blobs and strings. For ranges, I'm not sure if it's necessary since they don't expose `len` themselves.

**Comment by schungx** [comment]
Well they dont expose `len` but they do check for containment so I think it probably makes sense.

**Comment by ltabis** [comment]
If you are talking about the `RangeCase`, `is_empty` is already implemented just not exposed in rhai, is that ok ?

**Comment by schungx** [comment]
Sorry, I didn't make myself clear.

Methods on ranges are defined in `iter_basic.rs` under `mod range_functions`.

**Comment by ltabis** [comment]
Woops it's my bad, should I add `len` too ?

**Comment by ltabis** [comment]
I've updated it!

**Pull request merged**
