### PR TITLE
Fix compile on thumbv6m

### PR DESCRIPTION
**Pull request by chxry**

### CODE REVIEW

**Comment by chxry** [comment]
`critical-section` isn't supported on most targets, using it should be under a feature flag.

**Comment by schungx** [comment]
Oops. I merged it already.

Maybe I should reverse it?

**Comment by schungx** [comment]
But if it is available on a low end ARM, I suppose it is universal enough?

**Comment by chxry** [comment]
It only really exists on embedded systems, that change breaks building no_std_test. I've fixed it [here](https://github.com/chxry/rhai/commit/09bccd032d1c3f151c2d51a4053372b5d5fb748f) and can create a new PR.

**Comment by schungx** [comment]
Pls do. I don't do embedded and so I cannot test myself.

**Pull request merged**
