### PR TITLE
fuzz: Fix build

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
The last two builds for rhai have failed on oss-fuzz https://oss-fuzz-build-logs.storage.googleapis.com/index.html#rhai

This is my fault, I didn't properly `git add` things in my last PR and I also didn't configured the CI correctly, so the CI falsey reported that everything was ok. [This](https://github.com/rhaiscript/rhai/blob/main/.github/workflows/oss-fuzz.yml#L5) should be main instead of master.

**Comment by silvergasp** [comment]
I tested all this locally and it's building fine again. I've also (hopefull) fix up the oss-fuzz github action in #811

**Comment by schungx** [comment]
@silvergasp   For reasons I don't understand, the fuzz build has been failing for months now...  and it seems that all other projects in OSS-Fuzz have been failing.

Can you possibly look into this matter?

**Comment by silvergasp** [comment]
Sure I'll take a look now.

**Comment by silvergasp** [comment]
Fixed in https://github.com/google/oss-fuzz/pull/12409

Sorry I didn't catch this earlier, I don't receive notifications for failing builds.

**Comment by schungx** [comment]
Strange that most of the projects have builds that are failing...

**Comment by schungx** [comment]
@nathaniel-brough   sorry to bother you... but some of the fuzz builds have been failing again...  not sure what it is.

https://oss-fuzz-build-logs.storage.googleapis.com/log-c636c89b-2c30-40a9-910f-3739bae67bdd.txt

**Comment by nathaniel-brough** [comment]
Looks like it's related to code-coverage reports. So fuzzing should still be working fine, it's just that code-coverage isn't being collected. Unless you are using the coverage reports you can safely ignore that build failure. 

Never the less, I'll see if I can trouble shoot and get back to you.

**Comment by schungx** [comment]
Great! No wonder it looks like all the builds are ok but then it still keeps telling me something is failing...

**Pull request merged**
