### PR TITLE
add test for f32 + serde

### PR DESCRIPTION
**Pull request by dmadisetti**
This fails locally

image

seeing if it breaks the action too

### CODE REVIEW

**Comment by dmadisetti** [comment]
`et voila`

@schungx just an FYI. This might be a trivial fix- I haven't looked at it at all. I might find time either tonight or tomorrow night (NY time)

**Comment by dmadisetti** [comment]
Woops. That might just be the tests though. Anyway, leaving this for later

**Comment by schungx** [comment]
Yes, thanks for catching this.  The combination of `serde+f32_float` pops out this typo.

With the number of feature flags, it sometimes get hard not to miss certain combinations...

I'll fix the typo directly in the code and add `serde,metadata,internals` to `f32_float` in CI.

**Comment by schungx** [comment]
Fixed by https://github.com/rhaiscript/rhai/pull/390

**Pull request closed without merging**
