### PR TITLE
Fix Unix CI for no-std

### PR DESCRIPTION
**Pull request by Friz64**
Took a bit of digging until i found the issue i was looking for.

https://github.com/rust-lang/rust/issues/79609

### CODE REVIEW

**Comment by schungx** [comment]
Can you push the PR to my dev repo: https://github.com/schungx/rhai

It makes it easier for me to merge this into the current stream.

**Comment by schungx** [comment]
Maybe we shouldn't eliminate `rust_eh_unregister_frames`... not sure if it'll be used elsewhere  somewhere...

How about just adding `_Unwind_Resume`?

**Comment by Friz64** [comment]
> How about just adding `_Unwind_Resume`?

This is exactly what this PR is doing, no?

**Comment by Friz64** [comment]
> Can you push the PR to my dev repo

https://github.com/schungx/rhai/pull/63

**Pull request closed without merging**
